# Generated by Django 5.2.7 on 2025-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve doctor before they can login'),
        ),
    ]
